# advice_data.py - General safe advice for all 41 conditions in the dataset
ADVICE = {
    'Fungal infection': 'Keep the affected area clean and dry. Wear loose clothing and avoid sharing personal items.',
    'Allergy': 'Identify and avoid triggers. Use a cool compress to soothe itching. Consult an allergist.',
    'GERD': 'Avoid large meals and acidic foods. Maintain an upright posture after eating.',
    'Chronic cholestasis': 'Follow a low-fat diet and stay hydrated. Consult a specialist for liver health.',
    'Drug Reaction': 'Stop taking the suspected medication immediately and seek medical attention.',
    'Peptic ulcer diseae': 'Avoid spicy foods, caffeine, and alcohol. Eat small, frequent meals.',
    'AIDS': 'Maintain a highly nutritious diet and follow up with a healthcare provider regularly.',
    'Diabetes': 'Monitor blood sugar levels. Limit sugar intake and engage in regular physical activity.',
    'Gastroenteritis': 'Drink plenty of fluids (ORS) to prevent dehydration. Stick to a bland diet (BRAT).',
    'Bronchial Asthma': 'Keep an inhaler nearby. Avoid dust and smoke. Practice deep breathing exercises.',
    'Hypertension': 'Reduce salt intake. Exercise regularly and practice stress-management techniques.',
    'Migraine': 'Rest in a dark, quiet room. Stay hydrated and maintain a consistent sleep schedule.',
    'Cervical spondylosis': 'Maintain good posture. Perform gentle neck exercises and avoid heavy lifting.',
    'Paralysis (brain hemorrhage)': 'Seek emergency medical help immediately. Physical therapy is often required.',
    'Jaundice': 'Rest completely. Consume a light, low-fat diet and drink fresh juices.',
    'Malaria': 'Seek professional medical treatment immediately. Use mosquito nets and stay hydrated.',
    'Chicken pox': 'Do not scratch the rashes. Use calamine lotion and stay isolated to prevent spread.',
    'Dengue': 'Monitor platelet count closely. Seek medical help and stay extremely hydrated.',
    'Typhoid': 'Drink only boiled or bottled water. Consume a soft diet and see a doctor immediately.',
    'hepatitis A': 'Rest well and avoid alcohol. Eat small, high-calorie meals to maintain energy.',
    'Hepatitis B': 'Follow a balanced diet. Avoid alcohol and consult a liver specialist regularly.',
    'Hepatitis C': 'Seek specialist consultation. Avoid alcohol and maintain a healthy lifestyle.',
    'Hepatitis D': 'Requires specialized medical care. Avoid liver-taxing substances like alcohol.',
    'Hepatitis E': 'Rest and stay hydrated. Most people recover with supportive care under a doctor.',
    'Alcoholic hepatitis': 'Strictly avoid alcohol. Maintain a healthy diet and consult a specialist.',
    'Tuberculosis': 'Follow the full course of prescribed treatment. Maintain good ventilation and nutrition.',
    'Common Cold': 'Rest well, drink warm fluids, and stay hydrated with water or soups.',
    'Pneumonia': 'Get plenty of rest. Drink fluids and seek medical attention for breathing support.',
    'Dimorphic hemmorhoids(piles)': 'Eat high-fiber foods. Drink plenty of water and avoid straining during bowel movements.',
    'Heart attack': 'Emergency: Seek immediate medical attention. Do not delay.',
    'Varicose veins': 'Exercise regularly. Avoid standing for long periods and elevate your legs when resting.',
    'Hypothyroidism': 'Follow a balanced diet. Engage in regular exercise and monitor energy levels.',
    'Hyperthyroidism': 'Maintain a high-calorie, nutritious diet. Consult an endocrinologist.',
    'Hypoglycemia': 'Carry a source of fast-acting sugar. Eat regular meals to stabilize levels.',
    'Osteoarthristis': 'Maintain a healthy weight. Engage in low-impact exercises like swimming.',
    'Arthritis': 'Keep joints moving with gentle exercise. Use warm compresses to reduce stiffness.',
    '(vertigo) Paroymsal  Positional Vertigo': 'Move slowly when changing positions. Avoid sudden head movements.',
    'Acne': 'Keep skin clean with a gentle cleanser. Avoid touching your face or squeezing spots.',
    'Urinary tract infection': 'Drink plenty of water to flush the system. See a doctor for treatment.',
    'Psoriasis': 'Keep skin moisturized. Identify triggers like stress or cold weather.',
    'Impetigo': 'Keep sores clean and covered. Avoid touching the infected area to prevent spread.'
}

DEFAULT_ADVICE = 'Drink plenty of water, rest well, and consult a doctor if symptoms persist or worsen.'