# UI translations for the app
UI_LABELS = {
    'en': {
        'title': 'MediSense',
        'language': 'LANGUAGE',
        'voice_input': '🎤 Voice Input',
        'describe_symptoms': 'DESCRIBE YOUR SYMPTOMS',
        'placeholder_symptoms': 'e.g. fever and headache since yesterday with some nausea…',
        'analyze_btn': '🔍 Analyze Symptoms',
        'quick_select': 'QUICK SELECT',
        'selected_count': 'selected',
        'symptom_analyzer': 'Symptom Analyzer',
        'voice_backup_caption': 'Backup option: upload a recorded voice note if browser microphone access is unavailable.',
        'upload_voice': 'Upload voice backup (.wav or .flac)',
        'transcribe_btn': '⏺ Transcribe uploaded audio',
        'results': 'Analysis Results',
        'disease': 'Likely Condition',
        'confidence': 'Confidence',
        'recommendations': 'Recommendations',
        'remedies': 'Home Remedies',
        'medicine_reminder': 'Medicine Reminder',
        'set_reminder': 'Set Reminder',
        'medicine_name': 'Medicine Name',
        'time': 'Time',
        'save_reminder': 'Save Reminder',
        'info': 'Info & Settings',
        'disclaimer': 'Disclaimer',
        'features': 'Features',
        'listening': 'Listening…',
        'transcribing': 'Transcribing uploaded audio…',
        'running_diagnostic': 'Running diagnostic model…',
        'could_not_understand': 'Could not understand. Please speak more clearly and try again.',
        'error_audio': 'Could not understand the uploaded audio. Please use a clear .wav or .flac recording.',
        'no_symptoms': '⚠️ No recognizable symptoms found. Try describing in more detail or select from the chip panel.',
        'no_input': 'Please describe symptoms or pick from the Quick Select panel →',
        'speech_unavailable': 'Speech service unavailable. Check your internet.',
        'tab_analyzer': '  🩺  Analyzer  ',
        'tab_reminders': '  💊  Reminders  ',
        'tab_dashboard': '  📊  Dashboard  ',
        'tab_about': '  ℹ️  About  ',
        'tab_diet': '  🥗  Diet Planner  ',
        'tab_appointment': '  📅  Appointment  ',
    },
    'hi': {
        'title': 'मेडीसेंस',
        'language': 'भाषा',
        'voice_input': '🎤 वॉइस इनपुट',
        'describe_symptoms': 'अपने लक्षणों का वर्णन करें',
        'placeholder_symptoms': 'उदा. कल से बुखार और सिरदर्द कुछ मतली के साथ…',
        'analyze_btn': '🔍 लक्षणों का विश्लेषण करें',
        'quick_select': 'त्वरित चयन',
        'selected_count': 'चुने गए',
        'symptom_analyzer': 'लक्षण विश्लेषक',
        'voice_backup_caption': 'बैकअप विकल्प: यदि ब्राउज़र माइक्रोफोन एक्सेस उपलब्ध नहीं है तो रिकॉर्ड किए गए वॉइस नोट अपलोड करें।',
        'upload_voice': 'वॉइस बैकअप अपलोड करें (.wav या .flac)',
        'transcribe_btn': '⏺ अपलोड किए गए ऑडियो को ट्रांसक्राइब करें',
        'results': 'विश्लेषण परिणाम',
        'disease': 'संभावित स्थिति',
        'confidence': 'विश्वास',
        'recommendations': 'सिफारिशें',
        'remedies': 'घरेलू उपचार',
        'medicine_reminder': 'दवा रिमाइंडर',
        'set_reminder': 'रिमाइंडर सेट करें',
        'medicine_name': 'दवा का नाम',
        'time': 'समय',
        'save_reminder': 'रिमाइंडर सहेजें',
        'info': 'जानकारी और सेटिंग्स',
        'disclaimer': 'अस्वीकरण',
        'features': 'विशेषताएं',
        'listening': 'सुन रहे हैं…',
        'transcribing': 'अपलोड किए गए ऑडियो को ट्रांसक्राइब कर रहे हैं…',
        'running_diagnostic': 'डायग्नोस्टिक मॉडल चला रहे हैं…',
        'could_not_understand': 'समझ नहीं आया। कृपया अधिक स्पष्ट रूप से बोलें और पुनः प्रयास करें।',
        'error_audio': 'अपलोड किए गए ऑडियो को समझ नहीं आया। कृपया स्पष्ट .wav या .flac रिकॉर्डिंग का उपयोग करें।',
        'no_symptoms': '⚠️ कोई पहचानने योग्य लक्षण नहीं मिले। अधिक विस्तार से वर्णन करने का प्रयास करें या त्वरित चयन पैनल से चुनें।',
        'no_input': 'कृपया लक्षणों का वर्णन करें या त्वरित चयन पैनल से चुनें →',
        'speech_unavailable': 'स्पीच सेवा उपलब्ध नहीं है। अपना इंटरनेट जांचें।',
        'tab_analyzer': '  🩺  विश्लेषक  ',
        'tab_reminders': '  💊  अनुस्मारक  ',
        'tab_dashboard': '  📊  डैशबोर्ड  ',
        'tab_about': '  ℹ️  के बारे में  ',
        'tab_diet': '  🥗  आहार योजना  ',
        'tab_appointment': '  📅  अपॉइंटमेंट  ',
    },
    'kn': {
        'title': 'ಮೆಡಿಸೆನ್ಸ್',
        'language': 'ಭಾಷೆ',
        'voice_input': '🎤 ವಾಯ್ಸ್ ಇನ್ಪುಟ್',
        'describe_symptoms': 'ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ವರ್ಣಿಸಿ',
        'placeholder_symptoms': 'ಉದಾ. ನಿನ್ನೆಯಿಂದ ಜ್ವರ ಮತ್ತು ತಲೆನೋವು ಕೆಲವು ಅಸ್ವಸ್ಥತೆಯೊಂದಿಗೆ…',
        'analyze_btn': '🔍 ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
        'quick_select': 'ತ್ವರಿತ ಆಯ್ಕೆ',
        'selected_count': 'ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ',
        'symptom_analyzer': 'ರೋಗಲಕ್ಷಣ ವಿಶ್ಲೇಷಕ',
        'voice_backup_caption': 'ಬ್ಯಾಕಪ್ ಆಯ್ಕೆ: ಬ್ರೌಜರ್ ಮೈಕ್ರೋಫೋನ್ ಪ್ರವೇಶ ಲಭ್ಯವಿಲ್ಲದಿದ್ದರೆ ರೆಕಾರ್ಡ್ ಮಾಡಿದ ಧ್ವನಿ ಟಿಪ್ಪಣಿ ಅಪ್ಲೋಡ್ ಮಾಡಿ.',
        'upload_voice': 'ವಾಯ್ಸ್ ಬ್ಯಾಕಪ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ (.wav ಅಥವಾ .flac)',
        'transcribe_btn': '⏺ ಅಪ್ಲೋಡ್ ಮಾಡಿದ ಆಡಿಯೋ ಅನುಲೇಖಿಸಿ',
        'results': 'ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳು',
        'disease': 'ಸಂಭಾವ್ಯ ಸ್ಥಿತಿ',
        'confidence': 'ವಿಶ್ವಾಸ',
        'recommendations': 'ಶಿಫಾರಸುಗಳು',
        'remedies': 'ಮನೆಯ ಉಪಚಾರಗಳು',
        'medicine_reminder': 'ಔಷಧ ಸ್ಮರಣೀಯ',
        'set_reminder': 'ಸ್ಮರಣೀಯ ಹೊಂದಿಸಿ',
        'medicine_name': 'ಔಷಧದ ಹೆಸರು',
        'time': 'ಸಮಯ',
        'save_reminder': 'ಸ್ಮರಣೀಯ ಉಳಿಸಿ',
        'info': 'ಮಾಹಿತಿ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್\u200cಗಳು',
        'disclaimer': 'ನಿರಾಕರಣೆ',
        'features': 'ವೈಶಿಷ್ಟ್ಯಗಳು',
        'listening': 'ಕೇಳುತ್ತಿದೆ…',
        'transcribing': 'ಅಪ್ಲೋಡ್ ಮಾಡಿದ ಆಡಿಯೋ ಅನುಲೇಖಿಸುತ್ತಿದೆ…',
        'running_diagnostic': 'ರೋಗನಿರ್ಣಯ ಮಾದರಿ ಚಲಾಯಿಸುತ್ತಿದೆ…',
        'could_not_understand': 'ತಿಳಿಯಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಹೆಚ್ಚು ಸ್ಪಷ್ಟವಾಗಿ ಮಾತನಾಡಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
        'error_audio': 'ಅಪ್ಲೋಡ್ ಮಾಡಿದ ಆಡಿಯೋ ತಿಳಿಯಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ಪಷ್ಟವಾದ .wav ಅಥವಾ .flac ರೆಕಾರ್ಡಿಂಗ್ ಬಳಸಿ.',
        'no_symptoms': '⚠️ ಯಾವುದೇ ಗುರುತಿಸಬಹುದಾದ ರೋಗಲಕ್ಷಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಹೆಚ್ಚು ವಿವರವಾಗಿ ವರ್ಣಿಸಲು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ತ್ವರಿತ ಆಯ್ಕೆ ಪ್ಯಾನೆಲ್ ನಿಂದ ಆಯ್ಕೆ ಮಾಡಿ.',
        'no_input': 'ದಯವಿಟ್ಟು ರೋಗಲಕ್ಷಣಗಳನ್ನು ವರ್ಣಿಸಿ ಅಥವಾ ತ್ವರಿತ ಆಯ್ಕೆ ಪ್ಯಾನೆಲ್ ನಿಂದ ಆಯ್ಕೆ ಮಾಡಿ →',
        'speech_unavailable': 'ಧ್ವನಿ ಸೇವೆ ಲಭ್ಯವಿಲ್ಲ. ನಿಮ್ಮ ಇಂಟರನೆಟ್ ಪರಿಶೀಲಿಸಿ.',
        'tab_analyzer': '  🩺  ವಿಶ್ಲೇಷಕ  ',
        'tab_reminders': '  💊  ಸ್ಮರಣೀಯಗಳು  ',
        'tab_dashboard': '  📊  ಡ್ಯಾಶ್ಬೋರ್ಡ್  ',
        'tab_about': '  ℹ️  ಬಗ್ಗೆ  ',
        'tab_diet': '  🥗  ಆಹಾರ ಯೋಜನೆ  ',
        # FIX: was broken/corrupted Kannada string — replaced with clean ASCII fallback
        'tab_appointment': '  📅  Appointment  ',
    }
}

def get_label(key, language='en'):
    """Get UI label in the specified language."""
    if language in UI_LABELS and key in UI_LABELS[language]:
        return UI_LABELS[language][key]
    # Fallback to English
    return UI_LABELS['en'].get(key, key)